name: CI

on:
  pull_request:
    branches: [main]
env:
  TURBO_API: "http://127.0.0.1:8585"
  TURBO_TEAM: "hono-universal-cache"
  TURBO_TOKEN: "hono-universal-cache-turbo-token"
  FORCE_COLOR: 2

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Turborepo Cache Server
        uses: brunojppb/turbo-cache-server@2.0.2
        env:
          PORT: "8585"
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_REGION: ${{ secrets.S3_REGION }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          S3_SERVER_SIDE_ENCRYPTION: "AES256"
          MAX_PAYLOAD_SIZE_IN_MB: "100"
      
      - uses: pnpm/action-setup@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build packages
        run: pnpm build --filter hono-universal-cache
      
      - name: Run tests
        run: pnpm --filter hono-universal-cache test
      
      - name: Type check
        run: pnpm --filter hono-universal-cache typecheck
